name: Build and test Python package

# adapted from https://github.com/mkoeppe/sage-numerical-backends-coin
on:
  push:
  pull_request:
  schedule:
    - cron: '0 13 * * 1'

jobs:
  conda_sage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: sage-cluster-pictures
        environment-file: environment.yml
        condarc-file: condarc.yml
        auto-activate-base: false
        python-version: ${{ matrix.python-version }}
    - name: Show conda info
      shell: bash -l {0}
      run: conda list
    - name: Run Tox
      shell: bash -l {0}
      run: tox
    - name: Commit documentation changes
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.7'
      shell: bash -l {0}

      run: |
        git clone https://github.com/alexjbest/cluster-pictures.git --branch gh-pages --single-branch gh-pages
        cp -r .tox/docs/tmp/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.7'
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: alexjbest/cluster-pictures
