name: Build and test Python package

# adapted from https://github.com/mkoeppe/sage-numerical-backends-coin
on: [push, pull_request]

jobs:
  conda_sage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7']
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: sage-nim
        environment-file: environment.yml
        condarc-file: condarc.yml
        auto-activate-base: false
        python-version: ${{ matrix.python-version }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Show conda info
      shell: bash -l {0}
      run: conda list
    - name: Run Tox
      # Run tox using the version of Python in `PATH`
      run: tox -e py
